### ISSUE TITLE
经验分享：怎样修改一个 model 对应的 i18n, routes 等众多名称引用

### ISSUE THREAD

**Issue by ben7th** [mindpin/tech-exp#15]
比如 KnowledgeCamp 工程中用到的 `KnowledgeNetStore::Net` 这个类，在 i18n 文件里对应的名称引用是：

``` yaml
zh:
  mongoid:
    models:
      knowledge_net_store/net: 知识网络
```

现在我觉得这样带着 namedspace 很麻烦，想让他对应到

``` yaml
zh:
  mongoid:
    models:
      net: 知识网络
```

怎么办呢？

---

又比如我写 `form` , 或者 `link_to` 的时候，如果不显式指定 url，那么 rails 就会尝试去找 `knowledge_net_store_nets_path` 这样的 URL。但是我希望他去找 `nets_path` (因为我 routes 配置里是这么写的) 应该怎么办呢？

毕竟如果经常显式指定 URL，就享受不到 rails 的很多好处了。

---

以上两者解决方法都很简单（是不是最佳实践我不清楚，但奏效）.

用猴子补丁，在 initializers 里面随便写一个文件来声明：

``` ruby
module KnowledgeNetStore
  class Net
    def self.model_name
      ActiveModel::Name.new(KnowledgeNetStore::Net, nil, 'net')
    end
  end
end
```

就可以了。相关的很多名称引用都会变化。
灵活的使用这个机制，可以按我们的想法配置 routes，而类放在 module 里，便于集成。同时当修改 routes 配置时，view 层可以改动很少。

---

这个方式应该也能彻底解决许多关于类的名称的问题，省得像以前一样在工程里写一个类去继承 Gem 里面的类这种比较傻的方式。

---

这样也能比较优雅的解决
https://github.com/mindpin/generic_controller
GEM 中 `:require_name` 参数原本要解决的问题，减少声明代码。
